export enum IpcChannel {
    GetCompanies = 'get-companies',
    GetCountries = 'get-countries',
    FetchJobs = 'fetch-jobs',
    OpenUrl = 'open-url',
    OpenUrlBrowser = 'open-url-browser',
    ToggleSaveJob = 'toggle-save-job',
    GetSavedJobs = 'get-saved-jobs',
    ApplyJob = 'apply-job',
    GetAppliedJobs = 'get-applied-jobs',
    OnUpdateProgress = 'on-update-progress',
    GetPreferences = 'get-preferences',
    SavePreferences = 'save-preferences',
    GetNewPostings = 'get-new-postings',
    SaveNewPostings = 'save-new-postings',
}