name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    env:
      IS_TAG_RELEASE: ${{ github.event.head_commit.message matches '^v[0-9]+\.[0-9]+\.[0-9]+$' }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'

      - name: Package Electron
        if: ${{ !env.IS_TAG_RELEASE }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npm run electron-package

      - name: Package and Publish Electron
        if: ${{ env.IS_TAG_RELEASE }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npm run electron-publish

      - name: Build Changelog
        if: ${{ env.IS_TAG_RELEASE }}
        id: changelog
        uses: ardalanamini/auto-changelog@v4
        with:
          mention-authors: false
          mention-new-contributors: false
          include-compare-link: false
          semver: false

      - name: Update GitHub Release
        if: ${{ env.IS_TAG_RELEASE }}
        uses: ncipollo/release-action@v1.20.0
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          allowUpdates: true
          tag: ${{ github.event.head_commit.message }}
          name: Release ${{ github.event.head_commit.message }}
          token: ${{ secrets.GITHUB_TOKEN }}
